INSERT INTO PERSON (FIRST_NAME, LAST_NAME, ADDRESS, GENDER) VALUES ('Minh Hiep 1', 'Ho', 'HCMC, Vietnam','Male');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, ADDRESS, GENDER) VALUES ('Minh Hiep 2', 'Ho', 'HCMC, Vietnam','Male');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, ADDRESS, GENDER) VALUES ('Minh Hiep 3', 'Ho', 'HCMC, Vietnam','Male');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, ADDRESS, GENDER) VALUES ('Minh Hiep 4', 'Ho', 'HCMC, Vietnam','Male');
